### PR TITLE
callLater for thread safety

### PR DESCRIPTION
**Pull request by aferust**
Dear Adam,

I asked if minigui is thread-safe, and you said that you don't know almost a year ago. I implemented it please do your tests.

```d
import std.concurrency;

import arsd.minigui;

LineEdit text1;

void main() {
	auto window = new MainWindow();

	auto exitAction = new Action("E&xit");
	exitAction.triggered ~= { window.close(); };

	window.statusTip = "D ROX!";

	auto vl = new VerticalLayout(window);

	text1 = new LineEdit(vl);
	auto button1 = new Button("Hmm", vl);

	button1.addEventListener(EventType.triggered, () {
		spawn((){
			// callLater(delegate(){ // uncomment me for thread safety
				text1.content = "Hmm";
			// }); // uncomment me for thread safety
			
		});
		
	});


	window.loop();
}
```

### CODE REVIEW

**Comment by adamdruppe** [comment]
Actually since then I made something better... you can

http://dpldocs.info/experimental-docs/arsd.simpledisplay.runInGuiThread.html

runInGuiThread now!

**Comment by 0xEAB** [comment]
> Did you know you can use UFCS on delegate literals?

neat :)

**Comment by aferust** [comment]
> Actually since then I made something better... you can
> 
> http://dpldocs.info/experimental-docs/arsd.simpledisplay.runInGuiThread.html
> 
> runInGuiThread now!

Hey c'mon. You took my chance for contributing :-D.

**Comment by adamdruppe** [comment]
yeah this came up because i wanted to do the integrated terminal emulator thing in terminal.d... and to retrofit old terminal code, i put the gui in a separate thread. (which i now kinda regret, i should have just had them communicate through a pipe but meh oh well)

this meant i needed some way to run stuff like menus in the appropriate thread and thus that little function was born. kinda hacky but seems to work.

**Pull request closed without merging**
