### PR TITLE
Functions to simplify the control of the arrow

### PR DESCRIPTION
**Pull request by MuriloMir**
I've added 2 functions that allow the user to control the position of the mouse arrow in a very easy and intuitive manner. The first is designed to move the arrow by the numbers x and y and the second uses the first one to move it to a specific x,y on the screen, in this case I needed to tell it to first move it by -10000 so it goes to the very edge of the screen, regardless of the screen size(I didn't know how else to do that). I hope you like it.

### CODE REVIEW

**Comment by adamdruppe** [comment]
This is in the wrong file, it probably belongs in simpledisplay with the SendInput function rather than the joystick module.

I can move it later though.

**Comment by MuriloMir** [comment]
But shouldn't simpledisplay be for actual image display and not for input control?

**Comment by adamdruppe** [comment]
On Mon, May 11, 2020 at 06:28:48PM -0700, Murilo Miranda wrote:
> But shouldn't simpledisplay be for actual image display and not for input control?

it does a bunch of things that relate to windows. mouse control is
already a part of that so this fits better there.

or it could be an all new module but too small for that really.

joystick is specifically about working with joystick and game controller
hardware.

**Comment by adamdruppe** [comment]
ok gonna close this one

**Pull request closed without merging**
