### PR TITLE
Add Pixmap Paint module

### PR DESCRIPTION
**Pull request by 0xEAB**
**Pixmap Paint** is supposed to become a 2D drawing companion library of Pixmap Presenter.

Bonus:
Makes Pixmap manipulation available without the sdpy dependency.

### CODE REVIEW

**Comment by adamdruppe** [comment]
nice

**Comment by adamdruppe** [comment]
you wanna merge these soon?

**Comment by 0xEAB** [comment]
Not really, this is still in the very early stages of development.

**Comment by 0xEAB** [comment]
Okay, so I’ve prepared the branch to be somewhat suitable for inclusion as an “early technology preview”.

**Comment by 0xEAB** [comment]
While still nowhere near finished, I think it’s good enough for an early tech preview release.
Also I think separating the pixmap functionality from the presenter is worth having in the initial tagged release of the latter.

**Pull request merged**
