### PR TITLE
com.d: support (multi-dimensional) array paramters

### PR DESCRIPTION
**Pull request by dkorpel**
This enables setting a range of cells in Excel like so:
```D
auto range = sheet.Range()(sheet.Cells()(5, 1), sheet.Cells()(9, 5));
string[][] val = [["A", "B", "C"], ["CCC", "D", "E"]];
range.Value() = val;
```

### CODE REVIEW

**Comment by adamdruppe** [comment]
nice. yeah a lot of these aren't too hard to implement i just never got around to them since i have barely actually used this irl.

curious, what kind of work are you doing? obviously excel something lol

**Comment by dkorpel** [comment]
> curious, what kind of work are you doing?

I work part-time for SARC now, which you might know from this article:

https://dlang.org/blog/2018/06/20/how-an-engineering-company-chose-to-migrate-to-d/

Can't say more than that currently lol.

**Comment by adamdruppe** [comment]
ah i see, i remember their talks, they've done a few interesting libs in D.

well nevertheless lemme know if there's anything you get stuck on and i can help

**Comment by dkorpel** [comment]
Thanks. I think this covers all the functionality I need, but we'll see. I'm already pleasantly surprised this code exists, Python's `win32com` module is hard to integrate with Pascal, and I wasn't looking forward to writing C-style COM code.

**Pull request merged**
