### PR TITLE
move files for a proper package layout

### PR DESCRIPTION
**Pull request by BBasile**
Move sources in `./src/arsd` and the libraries in `./lib`, which is more logical considering the module names. One advantage is that DCD completion works better. Also add a `.gitignore` to filter out dub meta stuff.

### CODE REVIEW

**Comment by andre2007** [comment]
Thanks a lot for creating the pr. Is there a reason you use "src" as source folder? I just wonder because the default folder from dub is named "source".

**Comment by andre2007** [comment]
Not all of the modules belongs to package arsd. E.g. "cidr.d" has no package. I think I also saw same modules which belongs to another package than "arsd".

**Comment by adamdruppe** [comment]
Sorry for the slow response, I've been out all day, but I really don't want to do this since the proposed directory structure wouldn't work well on my computer (here, everything lives in `~/arsd`.... but then again, that's actually a symlink to `~/program/lib/arsd` so maybe I can hack it and make it work).

But I also just hate the useless directories here on the github web interface. Good D tools and processes can handle this directory structure - if yours can't, you should fix the bugs in them...

**Comment by adamdruppe** [comment]
> E.g. "cidr.d" has no package.

that's a bug but that module is barely supported anyway. but i should change it; top-level module names I consider a terrible practice and don't use anymore in any new code (but for a while I did)

**Comment by BBasile** [comment]
> Is there a reason you use "src" as source folder? 

 `src` is also handled as a default location.

> Not all of the modules belongs to package arsd.

fixed. There was even a module from ketmar's iv (renamed as arsd.vortbis to avoid more folders).

**Pull request closed without merging**
