### PR TITLE
Fix PixmapPresenter not glClear()'ing as expected

### PR DESCRIPTION
**Pull request by 0xEAB**
Fixes a bug that is masked by #459 on many systems.

### CODE REVIEW

**Comment by 0xEAB** [comment]
To be clear, this does not fix #459. The latter just makes it less obvious what is going on here.

**Comment by adamdruppe** [comment]
you sure this is necessary? since the other buffer should never be seen until it swaps back to the front anyway...

**Comment by 0xEAB** [comment]
PixmapPresenter clears only when needed (not every frame).

So this fix is needed. Because as-is it clears the backbuffer only and continues to use the non-cleared frontbuffer.
Unless I misunderstood how these things are supposed to work.

**Comment by adamdruppe** [comment]
so we checked the man pages and swapping buffers leaves the thing in an undefined state after, meaning each frame should assume it is random and clear/redraw anyway...

**Comment by 0xEAB** [comment]
Yeah, let’s yeet these glClear tricks and do things the safe way.

**Comment by 0xEAB** [comment]
Afaict, this also makes resizing the window look so much smoother.

**Comment by 0xEAB** [comment]
Thanks for your support with solving that one!

**Pull request merged**
