### PR TITLE
Some improvements to nanovega

### PR DESCRIPTION
**Pull request by AsumFace**
- Support for external OpenGL and FreeType bindings
- Modernization of OpenGL calls
- Change of behavior of the mipmapping option (existing code may render differently with this change)
- Addition of a LOD bias for better render quality of textures

### CODE REVIEW

**Comment by adamdruppe** [comment]
Interesting, I'll have to test in a few of my use cases before I merge just to make sure nothing inadvertently broke, but from a quick glance it all looks right!

I should have time to test tomorrow night, so I'll get back to you then. Thanks for the PR!

**Comment by 0xEAB** [comment]
> Change of behavior of the mipmapping option (existing code may render differently with this change)

Any example what's going to break?

**Comment by AsumFace** [comment]
> Any example what's going to break?
Any code that sets both NoFiltering and GenerateMipmaps for images may experience a slight visual change and a memory usage increase (due to the generated mipmap). Since GenerateMipmaps is currently ineffective when NoFiltering is set, this combination is probably not used anywhere intentionally.

**Comment by adamdruppe** [comment]
well, it continued to work normally on my low-dependency test, so merged in!

**Comment by 0xEAB** [comment]
> Any code that sets both NoFiltering and GenerateMipmaps...

Thanks for clarifying :)

**Pull request merged**
