### PR TITLE
Implement "corner style" property for sdpy windows on Windows 11+

### PR DESCRIPTION
**Pull request by 0xEAB**
As discussed on Discord, here’s my PR to add this feature.
This reclaims the pixels otherwise lost to rounded window corners.

Tested on Windows 11 + Windows 10 (where it does nothing due to the lack of support for the underlying feature, but does not crash either).

For convenience reasons we currently provide a dummy for unsupported systems that stores the value in a field without further processing. (This is also used as a fallback on unsupported Windows versions.)

In my tests (cross-linking on Linux!) it also works without explicitly passing `dwmapi` to the linker.
Not sure about Windows and the MS linker though. I think we should keep it – even if it’s just for cleanness purposes.

In general, I’d appreciate if someone developing on Windows could give this a try; thanks!

<details>

<summary>Credit where credit is due…</summary>

- <https://github.com/mgba-emu/mgba/issues/3285>
- <https://dolphin-emu.org/blog/2024/09/04/dolphin-progress-report-release-2407-2409/#50-21462-windows-remove-rounded-corners-on-emulation-render-window-by-filoppi>

</details>

### CODE REVIEW

**Comment by adamdruppe** [comment]
cool. the use of Phobos is banned from simpledisplay, std.format in particular triples the compile time here, but ill fix that up for you

**Comment by adamdruppe** [comment]
actually, the whole `throw new Exception` thing sux, so ill replace it with one of the proper types from arsd.core

**Comment by adamdruppe** [comment]
https://github.com/adamdruppe/arsd/commit/ae07d697a39fa46a1c21c7870062c0330b78fe50

the `throw ArsdException!""()` thing is also lazy but at least keeps some structure over the plain naked exception string and i can fix it up l8r

**Comment by 0xEAB** [comment]
> but ill fix that up for you

thanks :)

**Pull request merged**
